mysite/formRobot/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.get_formRobot, name='get_formRobot'),
    path('execScript/', views.execScript),
]

mysite/gamesPage/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.page_jeux, name='page_jeux'),
    path('execScript/', views.execScript),
]

mysite/mainMenu/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.menu_principal, name='menu_principal'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('mainMenu.urls')),
    path('formRobot/', include('formRobot.urls')),
    path('gamesPage/', include('gamesPage.urls')),
    path('storyMode/', include('storyMode.urls')),
    path('storyOne/', include('storyOne.urls')),
    path('admin/', admin.site.urls),
]

mysite/storyMode/urls.py
from django.urls import include, path
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.mode_histoire, name='mode_histoire'),
    path('storyOne/', include('storyOne.urls')),
]

mysite/storyOne/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.histoire_un, name='histoire_un'),
    path('execScript/', views.execScript),
]

mysite/storyOne/models.py
from django.db import models

# Create your models here.

mysite/storyOne/forms.py
from django import forms

class NameForm(forms.Form):
    code = forms.CharField(widget=forms.Textarea, label='Votre code')

mysite/formRobot/views.py
from django.http import HttpResponseRedirect
from django.http.response import HttpResponse
from django.shortcuts import render 
import sys
from subprocess import run, PIPE

def get_formRobot(request):
    return render(request, 'template_formRobot.html')


def execScript(request):

    #print (request.POST.get('code'))
    filePath = '.\\MYSCRIPT.py';
    open(filePath, 'w').close()

    file_object = open(filePath, 'a')
    file_object.write(request.POST.get('code'));
    file_object.close();

    saveout = sys.stdout
    fsock = open('out.log', 'w')
    sys.stdout = fsock
    erreur = ""
    """
    with open("interface/scriptRobots/BaseQuestion.py") as programToExecute:
        try:
            exec(programToExecute.read())
        except Exception as error:
            erreur = error
    """
    try:    
        exec(open(filePath).read())
    except Exception as error:
        erreur = "Sortie erreur : " + str(error)
    
    
    sys.stdout = saveout
    fsock.close()
    fsockR = open('out.log', 'r')
    text = "Sortie standard : " + fsockR.read()

    fsockR.close()
    return render(request, 'template_formRobot.html', {'logs':text, 'error':erreur})

    ##out = run([sys.executable,filePath], shell=True,stdout=PIPE)
    ##return HttpResponse("")

mysite/gamesPage/views.py
from os import system
from django.http.response import HttpResponse
from django.shortcuts import render
from django.http import HttpResponseRedirect

from django.shortcuts import render 
import sys
from subprocess import run, PIPE

def page_jeux(request):
    return render(request, 'gamesPage.html')

def execScript(request):
    filePath = './gamesPage/jeux/' + request.POST.get('nomExo') + '.py'
    print(filePath)
    saveout = sys.stdout
    fsock = open('out.log', 'w')
    sys.stdout = fsock
    erreur = ""
    try:
        exec(open(filePath).read())
    except Exception as error:
        erreur = "Sortie erreur : " + str(error)
    
    sys.stdout = saveout
    fsock.close()
    fsockR = open('out.log', 'r')
    text = "Sortie standard : " + fsockR.read()
    fsockR.close()
    return render(request, 'gamesPage.html', {'logs':text, 'error':erreur})
    ##out = run([sys.executable,filePath], shell=True,stdout=PIPE)
    ##return HttpResponse(out)

mysite/mainMenu/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render

def menu_principal(request):
    return render(request, 'mainMenu.html')

mysite/storyMode/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render

def mode_histoire(request):
    return render(request, 'storyMode.html')

mysite/storyOne/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.http.response import HttpResponse
import sys
from subprocess import run, PIPE
from .forms import NameForm

def histoire_un(request):
    return render(request, 'storyOne.html')

def execScript(request):
    print (request.POST.get('code'))
    filePath = '.\\MYSCRIPT.py'
    open(filePath, 'w').close()

    file_object = open(filePath, 'a')
    file_object.write(request.POST.get('code'));
    file_object.close();
    saveout = sys.stdout
    fsock = open('out.log', 'w')
    sys.stdout = fsock
    try:
        exec(open(filePath).read())
    except Exception as error:
        print(error)
    sys.stdout = saveout
    fsock.close()
    fsockR = open('out.log', 'r')
    text = fsockR.read()
    fsockR.close()
    return render(request, 'storyOne.html', {'logs':text})

mysite/formRobot/templates/name.html
<form action="/formRobot/execScript/" method="post">
    {% csrf_token %}
    <textarea tabindex="-1" name="code" cols="150" rows="30" required="" id="id_code"></textarea>
    <input type="submit" value="Submit">
</form>

<script>
    document.querySelector('#id_code').addEventListener('keydown', e => {
        if ( e.key === 'Tab' && !e.shiftKey ) {
            // execCommand operations are "Cmd|Ctrl+Z"-able
              // note: execCommand is deprecated and may not work in the future
            document.execCommand('insertText', false, "\t");
            e.preventDefault();
            return false;
        }
    });
</script>

mysite/formRobot/templates/template_formRobot.html
<h1>Titre</h1>

<form action="/formRobot/execScript/" method="post">
    {% csrf_token %}
    <textarea tabindex="-1" name="code" cols="150" rows="30" required="" id="id_code"></textarea>
    <br/>
    <br/>
    <input type="submit" value="Submit" style="height:50px; width:100px">
</form>
<br/>

{% if logs %}
    <p>
        {{logs}}
    </p>
{% endif %}
{% if error %}
    <p>
        {{error}}
    </p>
{% endif %}

<script>
    document.querySelector('#id_code').addEventListener('keydown', e => {
        if ( e.key === 'Tab' && !e.shiftKey ) {
            // execCommand operations are "Cmd|Ctrl+Z"-able
              // note: execCommand is deprecated and may not work in the future
            document.execCommand('insertText', false, "\t");
            e.preventDefault();
            return false;
        }
    });
</script>

mysite/gamesPage/templates/gamesPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Jeux</title>
    <link rel="stylesheet" href="../../static/css/gamesPage.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>
<br>
{% if logs %}
    <p>
        {{logs}} 
    </p>
{% endif %}
{% if error %}
    <p>
        {{error}}
    </p>
{% endif %}
<div id="containerPenseAUnNombre" class="container">
        <h3>Je pense à un nombre</h3>
            <img src="../../static/media/fakegame_1.jpg">
        <form action="/gamesPage/execScript/" method="post" hidden>
            {% csrf_token %}
            <textarea tabindex="-1" name="nomExo" id="nomExo">findNumber</textarea>
            <input id="btnfindNumber" type="submit" value="Submit">
        </form>
    </div>
<br>
<div id="containerquestion_v3_avecVocal" class="container">
        <h3>Questionnaire</h3>
            <img src="../../static/media/fakegame_2.jpg">
        <form action="/gamesPage/execScript/" method="post" hidden>
            {% csrf_token %}
            <textarea tabindex="-1" name="nomExo" id="nomExo">question_v2_sansVocal</textarea>
            <input id="btnquestion_v3_avecVocal" type="submit" value="Submit">
        </form>
</div>
</body>
</html>

<script>
    let exoPenseAUnNombre = document.getElementById("containerPenseAUnNombre");
    exoPenseAUnNombre.onclick = function() {
        document.getElementById("btnfindNumber").click();
    }
    let exoquestion_v3_avecVocal = document.getElementById("containerquestion_v3_avecVocal");
    exoquestion_v3_avecVocal.onclick = function() {
        document.getElementById("btnquestion_v3_avecVocal").click();
    }


</script>

mysite/mainMenu/templates/mainMenu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Menu principal</title>
    <link rel="stylesheet" href="../../static/css/mainMenu.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>
<br>
<div class="container">
  <div class="row">
    <div class="col">
        <h3>Jeux</h3>
        <a href="gamesPage">
            <img class="hoverable" src="../../static/media/cozmo_1.jpg">
        </a>
    </div>
    <div class="col">
        <h3>Mode libre</h3>
        <a href="formRobot">
            <img src="../../static/media/cozmo_2.jpg">
        </a>
    </div>
  </div>
    <br>
  <div class="row">
    <div class="col">
        <h3>Histoire</h3>
        <a href="storyMode">
            <img src="../../static/media/cozmo_3.jpg">
        </a>
    </div>
    <div class="col">
        <h3>Admin</h3>
        <a href="https://www.king-jouet.com/jeu-jouet/mediatheque-jeux-videos/jeux-jouets-electroniques/ref-739801-robot-cozmo-anki.htm">
            <img src="../../static/media/cozmo_4.jpg">
        </a>
    </div>
  </div>
</div>
</body>
</html>

mysite/storyMode/templates/storyMode.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mode histoire</title>
    <link rel="stylesheet" href="../../static/css/storyMode.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>
<br>
<div class="container">
    <h3>Histoire 1</h3>
    <a href="storyOne">
        <img class="hoverable" src="../../static/media/cozmo_1.jpg">
    </a>
</div>
</body>
</html>

mysite/storyOne/templates/storyOne.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Les J.O. d'Hiver</title>
    <link rel="stylesheet" href="../../static/css/storyOne.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
<br>
<h1 style="align-content: center; text-align: center; color: cornflowerblue;">Les J.O. d'Hiver</h1>
<br>
<p class="lead" style="text-align: center !important; align-items: center !important; margin-left: 5%; margin-right: 5%;">
    <strong>Toto le robot est la toute nouvelle mascotte</strong> des Jeux Olympiques d'Hiver de Pékin.
    <br>Toutes les épreuves se déroulaient bien, jusqu'à ce que les organisateurs se rendent compte qu'ils avaient <strong>oublié le podium</strong>...
    <br>Comment va-t-on faire ? Comment savoir qui aura gagné la <strong>première place</strong> ?
    <br><br>Malheureusement tous les engins de chantier sont à des kilomètres, la première épreuve se termine dans quelques dizaines de minutes…
    <br>Seul un petit <strong>robot serait assez fort pour porter ses blocs</strong>, <strong>construire un podium</strong> et <strong>célébrer la performance des athlètes</strong>.
    <br><br><strong>Aide-le à retrouver tout les blocs</strong> et à <strong>construire le podium en les plaçant dans le bon ordre</strong> :
    <br>• 1er en haut : Jaune
    <br>• 2ème en bas à gauche : Bleu
    <br>• 3ème en bas à droite : Rouge
    <br><br><strong>Fais vite avant que la dernière épreuve ne se termine</strong> !
    <br>Et bonne chance ! 🙏

</p>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="../../static/media/fakegame_4_resized.jpg" alt="Premier exercice">
            <div class="carousel-caption d-none d-md-block" style="top: 60%; transform: translateY(-60%); background-color: white; box-shadow: 0 6px 10px rgba(0,0,0,.08), 0 0 6px rgba(0,0,0,.05); opacity: 0.88;">
                <h4 style="color: black">Exercice 1</h4>
                <p style="color: black">Se familiariser avec le robot. Déplacement basique, déplacement jusqu'à un cube.
                    <br><br>• Faites le avancer d’une distance n, faire un demi tour et revenir au point de départ.
                    <br>• Faites le avancer d’une distance n, faire un grand virage vers la droite ou la gauche, jusqu'à revenir au point de départ.
                    <br>• Faites en sorte que Toto puisse se déplacer en direction d’un cube, attention à ce qu’il ne fasse pas d’accident tout de même !
                    <br>
                </p>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="https://placeimg.com/1080/500/arch" alt="Deuxième exercice">
            <div class="carousel-caption d-none d-md-block" style="top: 60%; transform: translateY(-60%); background-color: white; box-shadow: 0 6px 10px rgba(0,0,0,.08), 0 0 6px rgba(0,0,0,.05); opacity: 0.88;">
                <h4 style="color: black">Exercice 2</h4>
                <p style="color: black">Paramétrer les couleurs sur les différents cubes, configurer Cozmo pour les reconnaître.
                    <br><br>• Faites s’allumer les différents cubes dans les trois couleurs du podium.
                    <br>• Positionner les différents cubes de couleurs autour de lui, faites en sorte qu’il reconnaisse la couleur de l’un d’eux (la couleur de votre choix) et qu’il se tourne vers lui.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="https://placeimg.com/1080/500/nature" alt="Troisième exercice">
            <div class="carousel-caption d-none d-md-block" style="top: 60%; transform: translateY(-60%); background-color: white; box-shadow: 0 6px 10px rgba(0,0,0,.08), 0 0 6px rgba(0,0,0,.05); opacity: 0.88;">
                <h4 style="color: black">Exercice 3</h4>
                <p style="color: black">Combinaison des exercices, former un podium (style pyramide de cube), avec les couleurs et l'ordre donné.
                    <br><br>• C’est le moment de construire, il ne vous reste plus beaucoup de temps !
                    <br>• Toto doit utiliser ses nouvelles connaissances (grâce à vous) et construire le podium, attention à respecter l’ordre des couleurs donné plus tôt.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="https://placeimg.com/1080/500/nature" alt="Quatrième exercice">
            <div class="carousel-caption d-none d-md-block" style="top: 60%; transform: translateY(-60%); background-color: white; box-shadow: 0 6px 10px rgba(0,0,0,.08), 0 0 6px rgba(0,0,0,.05); opacity: 0.88;">
                <h4 style="color: black">Exercice 4</h4>
                <p style="color: black">Célébrer la victoire des athlètes avec un petit discours...
                    <br><br>• Toto doit féliciter les différents athlètes.
                    <br>• Faites-le se positionner devant chacun d’eux et dire quelques mots de félicitations en fonction de leurs médailles (Or, Argent, Bronze).</p>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<div class="container" style="margin-top: 220px; margin-left: 400px;">
    <form action="/storyOne/execScript/" method="post">
        {% csrf_token %}
        <textarea tabindex="-1" name="code" cols="50" rows="10" required="" id="id_code" style="top: 60%; transform: translateY(-60%);"></textarea>
        <input type="submit" value="Lancer le code">
    </form>
    {% if logs %}
    <p>
        {{logs}} 
    </p>
{% endif %}
</div>
</body>
</html>